development:
  adapter: postgresql
  encoding: unicode
  database: pionerosdbdev
  username: pionerosuser
  password: '9zFU5L0iZGnDlE5Gry6a'
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: pionerosdbtest
  username: pionerosuser
  password: '9zFU5L0iZGnDlE5Gry6a'
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: pionerosdbp
  username: pionerosuser
  password: '9zFU5L0iZGnDlE5Gry6a'
  host: localhost